- app/models/category.rb
- db/migrate/20210824161710_create_categories.rb
- db/schema.rb
- test/models/category_test.rb
> create Category model

- db/seeds.rb
@vanthaohuynh Please take a look at the seed file I created
> Finish a first draft of the seed file without organizations and connections

- db/seeds.rb
@vanthaohuynh fixed a typo in seeds file plus removed empty line
> fixed typo and empty line in seed file

- app/views/organizations/show.html.erb
It might be need in case Van is not using an email app for the presentation. 🕸️
> Add target blank to mail_to on org show

- app/assets/stylesheets/components/_card.scss
- app/views/components/_card.html.erb
- app/views/organizations/curated.html.erb
- app/views/pages/home.html.erb
Linked the curated card iteration with card html/css, so that on the curated results page the results display as cards
> added cards to curated search results

- app/controllers/journal_entries_controller.rb
- app/controllers/organizations_controller.rb
- app/models/journal_entry.rb
- app/models/user.rb
- app/views/journal_entries/new.html.erb
- app/views/organizations/my_organizations.html.erb
- config/routes.rb
- db/migrate/20210830154150_create_journal_entries.rb
- db/schema.rb
- test/controllers/journal_entries_controller_test.rb
- test/models/journal_entry_test.rb
Please review: Created journal entry model, controller, routes and my_volunteering page
> Create journal entry model

- app/assets/stylesheets/components/_explore_card.scss
- app/assets/stylesheets/components/_hero.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/home.scss
- app/views/components/_navbar.html.erb
- app/views/pages/home.html.erb
didn't actually align it yet LOL but did make the nav smaller as well as the avatar image
> made navbar smaller, made avatar image smaller

- app/views/profiles/_interest_fields.html.erb
- app/views/profiles/_location_fields.html.erb
> added placeholders and removed labels

- app/controllers/journal_entries_controller.rb
- app/views/journal_entries/index.html.erb
- app/views/organizations/my_organizations.html.erb
- config/routes.rb
> implement journal entry index page

- app/views/components/_navbar.html.erb
- app/views/layouts/application.html.erb
- app/views/organizations/curated.html.erb
- app/views/pages/home.html.erb
> added navbar component to application.html.erb

- app/views/components/_navbar.html.erb
we can now access multiple pages through the avatar in the navbar
> added drop down menu accessible through avatar icon

- app/models/journal_entry.rb
- app/views/journal_entries/index.html.erb
- app/views/journal_entries/new.html.erb
- app/views/organizations/show.html.erb
> implement emoji picker

- app/assets/stylesheets/components/_explore_card.scss
- app/views/components/_explore_card.html.erb
- app/views/pages/home.html.erb
@eytienne87 just added a few placeholder cards on the landing page, to be linked to seeds on a subsequent branch
> placeholder cards added to explore section of landing page

- app/views/organizations/my_organizations.html.erb
> change new journal entry icon

- db/seeds.rb
> fixed bug with seed file

- app/views/components/_curated-card.html.erb
round 1 of curated card updates: this adds dimension, location, hashtags, and changes the internal layout
> added placeholder html for curated cards

- app/assets/stylesheets/components/_explore-card.scss
- app/views/components/_explore-card.html.erb
changed the style and html of explore cards to that of the recently blinged-out curated cards
> applied style and html of curated cards to explore cards on landing page

- app/assets/stylesheets/components/_curated-card.scss
- app/assets/stylesheets/components/_explore-card.scss
- app/views/components/_curated-card.html.erb
- app/views/organizations/curated.html.erb
@caioertai obrigada // linking curated organization attributes to curated cards
> Recommended card changes

- app/controllers/journal_entries_controller.rb
2 fixes:
- Fix emoji error on new journal entry page: "Emoji is not on the list"
- Change redirect_to to Journal entry index after saving new journal entry.
Please review. Thanks
> fix emoji error on new journal entry page

- app/assets/stylesheets/components/_curated-card.scss
changed text color and spacing within curated cards and on curated card page
> corrected card styling issues for curated cards

- app/controllers/journal_entries_controller.rb
- app/models/journal_entry.rb
> Modify JournalEntry model to add new icons to EMOJIS list

- app/assets/stylesheets/pages/edit.scss
- app/views/profiles/_form.html.erb
- app/views/profiles/_interest_fields.html.erb
> adjusted the buttons on the page, they look better for now

- app/controllers/journal_entries_controller.rb
- app/controllers/organizations_controller.rb
- app/models/organization.rb
- app/views/organizations/show.html.erb
> add logic to hide the send form in org show page

- app/assets/stylesheets/components/_explore-card.scss
- app/assets/stylesheets/components/_hero.scss
- app/assets/stylesheets/pages/home.scss
- app/views/components/_hero.html.erb
changed padding/margins on home page headers and hero
> spacing better on home; page is prepped for image drop

- app/controllers/profiles_controller.rb
- app/views/components/_navbar.html.erb
- app/views/profiles/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Created profile show page; added show view, profiles_controller#show; added relevant route; pointed link in navbar avatar to relevant route; built html structure as per Figma
Please @eytienne87 review
> Created profile show page

- public/404.html
- public/500.html
> modify 404 and 500 page

- app/assets/stylesheets/pages/edit.scss
- app/views/profiles/_interest_fields.html.erb
- app/views/profiles/_location_fields.html.erb
self explanatory @vanthaohuynh please review
> fixed alignment of delete buttons

- app/views/components/_navbar.html.erb
@stephane let me know what you think of this name?
> changed link name

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/journal.scss
- app/views/journal_entries/index.html.erb
> Styling journal entry index page

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/organizations_controller.rb
- app/views/components/_hero.html.erb
- app/views/layouts/application.html.erb
- app/views/profiles/_form.html.erb
- app/views/shared/_flashes.html.erb
Changed text of button to `Volunteer now!`
Changed target of button to `organizations_controller#curated` instead of `profiles_controller#edit`
Changed title of `profile#show`
Added rendering of `flash` messages
@eytienne87 , please review
> Modified behaviour and text of explore button on home page

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/edit.scss
- app/assets/stylesheets/pages/new.scss
- app/models/journal_entry.rb
- app/views/journal_entries/new.html.erb
> finished styling the emoji form

- app/controllers/profiles_controller.rb
- app/views/profiles/_form.html.erb
button on profile page says "save" and not "submit"; button redirects to profile page instead of curated page
> Update profile edit page

- app/assets/stylesheets/pages/new.scss
- app/views/journal_entries/new.html.erb
> added the label for the content input on new journal entry page

- app/assets/stylesheets/pages/new.scss
- app/models/journal_entry.rb
> finished the 'my journal entry' page with esteban's help

- app/assets/stylesheets/components/_navbar.scss
> changed placeholder text color in nav search bar

- app/javascript/components/alert_after_contact.js
- app/javascript/packs/application.js
- app/views/organizations/show.html.erb
- package.json
- yarn.lock
Added alert after contacting an organization, and implemented Sweet Alert
@vanthaohuynh  please review
> Add alert after contact org

- app/controllers/journal_entries_controller.rb
- app/controllers/profiles_controller.rb
- app/views/journal_entries/index.html.erb
Please review
Redirects to curated list on profile create / edit
Create initial entry when contacting an org
> Changed redirects & added default initial entry

- app/assets/stylesheets/pages/new.scss
> fix emoji display

- app/assets/stylesheets/pages/journal.scss
> journal entry update

- app/assets/stylesheets/pages/journal.scss
> fix bug with emoji class

- app/assets/stylesheets/components/_navbar.scss
- app/views/components/_navbar.html.erb
> navbar fix border

- app/assets/stylesheets/pages/show.scss
- app/views/organizations/show.html.erb
> update org show page

- db/seeds.rb
> change seed file

- app/javascript/components/alert_after_contact.js
- app/javascript/packs/application.js
- app/views/components/_hero.html.erb
- app/views/profiles/_form.html.erb
changing text in profile form and alert
> Changing form fext

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- Add style to sessions new
- Style registrations new
- Styled forgot your password
- Add headings to sign up and login
> style devise views

- db/seeds.rb
> change category name in seed file
